[build]
  command = "npm install --legacy-peer-deps --force && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "9.8.1"
  CI = "false"
  NODE_OPTIONS = "--openssl-legacy-provider"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
